version: "2"

services:
  server:
    image: nginx
    volumes:
      - ./conf.d/rotRL.conf:/etc/nginx/conf.d/rotRL.conf
      - ./www:/var/www
    ports:
      - "8888:8888"
    environment:
      - NGINX_HOST=rotRL
      - NGINX_PORT=8888
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/rotRL.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

